### ISSUE TITLE
Patching user connection permissions

### ISSUE THREAD

**Issue by jlunde-cisco** [scicore-unibas-ch/ansible-modules-guacamole#22]
If I create a new connection, and then attempt to give the user permission to that connection (without referencing all of the existing connections), the PATCH does not seem to take. For example, if for every host I build, I run this play:
```
- name: Add connection permission to existing user
  scicore.guacamole.guacamole_user:
    base_url: "{{ guac_url }}"
    auth_username: "{{ guac_user }}"
    auth_password: "{{ guac_pass }}"
    username: "{{ cco_username }}"
    allowed_connections:
      - "{{ ansible_hostname }}"
```
simply attempting to add {{ ansible_hostname }} to the existing list of connections, it essentially is never doing so.

**Comment by pescobar** [comment]
can you provide more details? Please share the complete playbook creating the connections and then granting permissions. What guacamole version are you using? what type of connections you create on guacamole (rdp, vnc, ssh?)

I use this collection in a daily basis to create new guacamole rdp connections and grant permissions to them on latest guacamole release and it works fine for me

**Comment by shilky69** [comment]
Hello,

I have exactly the same problem when we use the scicore.guacamole.guacamole_user module and we want to authorize the user on several connections for example if we put: (allowed_connetion: host1, host2) --> it works

    - name: Add a new guacamole user
      scicore.guacamole.guacamole_user:
        base_url: https://******/guacamole
        auth_username: guacadmin
        auth_password: guacadmin
        username: user4
        password: Sdffgfgze1454
        full_name: "John"
        email: "aaaaa@hotmail.com"
        organization: "scicore"
        allowed_connections:
        -host1
        - host2
      register:_user_info
    - debug:
        var:_user_info

On the other hand, if you want to pass several hosts via a with_items for example, it only takes the last host. How to add multiple hosts dynamically? :

    - name: Add a new guacamole user
      scicore.guacamole.guacamole_user:
        base_url: https://******/guacamole
        auth_username: guacadmin
        auth_password: guacadmin
        username: user4
        password: Sdffgfgze1454
        full_name: "John"
        email: "aaaaa@hotmail.com"
        organization: "scicore"
        allowed_connections:
        - "{{item}}"
      register:_user_info
   with_items:
     - hosts
    - debug:
        var:_user_info

**Comment by pescobar** [comment]
@shilky69  try like this

```
- name: Add a new guacamole user
  scicore.guacamole.guacamole_user:
    base_url: https://******/guacamole
    auth_username: guacadmin
    auth_password: guacadmin
    username: user4
    password: Sdffgfgze1454
    full_name: "John"
    email: "aaaaa@hotmail.com"
    organization: "scicore"
    allowed_connections: "{{ hosts }}"
  register:_user_info
 ```
