### ISSUE TITLE
using parent identifier in group_name does not work

### ISSUE THREAD

**Issue by paxprot** [scicore-unibas-ch/ansible-modules-guacamole#27]
I'm using mysql to store connections, when I use parent identifier in group_name to create connections the task will fail and return a msg like "Could not find the numeric id for connections group 48. Does the group exists?" My playbook is as follow:
```
- name: Create new vnc connections
  scicore.guacamole.guacamole_connection:
    base_url: {{ guac_url }}
    auth_username: {{ guac_user }}
    auth_password: {{ guac_password }}
    connection_name: {{ item.name }}
    protocol: vnc
    hostname: {{ item.hostname }}
    port: 5900
    password: {{ item.password }}
    max_connections: 10
    group_name: 48
  with_items:
    - ....
```
The actual group name works, the problem is that I have many folders and the task seems to take effect on the folder closer to ROOT. For a structure like this, I want to add connections to the folder 2 under folder 4, but they will be added to the folder 2 under folder 1.
```
├── folder1/
│   └── folder 2
└── folder 3/
    └── folder 4/
        └── folder 2
```
As a newbie to ansible, I'm stuck here. Does anybody have the same issue? Is there any suggestion?
